language: java
sudo: false
install:
  - jdk_switcher use oraclejdk8
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6
script:
  - jdk_switcher use oraclejdk7
  - mvn test -Dmaven.javadoc.skip=true -Dtest.excludes=**/ZipPreserveTimeStampJava8Test.java
  - jdk_switcher use openjdk7
  - mvn test -Dmaven.javadoc.skip=true -Dtest.excludes=**/ZipPreserveTimeStampJava8Test.java
  - jdk_switcher use openjdk6
  - mvn test -Dmaven.javadoc.skip=true -Dtest.excludes=**/ZipPreserveTimeStampJava8Test.java
