language: java
install:
  - jdk_switcher use oraclejdk8
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6
script: mvn test -Dmaven.javadoc.skip=true
