language: java
sudo: false
env:
  - MAVEN_OPTS="-Dmaven.javadoc.skip=true"
install:
  - jdk_switcher use oraclejdk8
  - mvn install -DskipTests=true
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6
script:
  - jdk_switcher use $TRAVIS_JDK_VERSION
  - mvn test
